const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { spawn } = require('node:child_process');
const { launchElectron } = require('./electron-driver.cjs');

async function main() {
  assert.equal(process.env.CONDA_DEFAULT_ENV, 'JK', 'Run this test in conda JK');
  const root = path.resolve(__dirname, '..');
  const output = path.join(root, '.qa');
  fs.mkdirSync(output, { recursive: true });
  const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'xiaojd-qa-'));
  const env = { ...process.env, XIAOJD_TEST_DATA: userData, XIAOJD_TEST_STATIC: '1' };
  delete env.ELECTRON_RUN_AS_NODE;
  const vite = spawn(process.execPath, [path.join(root, 'node_modules/vite/bin/vite.js'), '--host', '127.0.0.1', '--port', '1420'], { cwd: root, env, stdio: 'pipe', windowsHide: true });
  let application;
  try {
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('Vite startup timeout')), 20000);
      vite.stdout.on('data', (chunk) => { if (chunk.toString().includes('1420')) { clearTimeout(timer); resolve(); } });
      vite.stderr.on('data', (chunk) => process.stderr.write(chunk));
      vite.on('exit', (code) => { if (code) reject(new Error('Vite exit ' + code)); });
    });
    const launch = () => launchElectron(root, env);
    application = await launch();
    const page = await application.firstWindow();
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    page.on('console', (message) => { if (message.type() === 'error') console.log('CONSOLE', message.text()); });
    page.on('requestfailed', (request) => console.log('REQUEST FAILED', request.url(), request.failure()));
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.getByRole('button', { name: '选项', exact: true }).waitFor().catch(async (error) => {
      console.log('PAGE', page.url(), (await page.content()).slice(0, 4000), errors);
      console.log('WINDOWS', await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().map((window) => ({ url: window.webContents.getURL(), title: window.getTitle() }))));
      await page.screenshot({ path: path.join(output, 'startup-failure.png') });
      throw error;
    });
    await page.waitForFunction(() => Boolean(window.desktop));
    await page.screenshot({ path: path.join(output, 'wheel-desktop.png') });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.getByRole('button', { name: '选项', exact: true }).click();
    await page.getByRole('dialog', { name: '转盘选项' }).waitFor();
    await page.screenshot({ path: path.join(output, 'wheel-options.png') });
    const choices = page.locator('.floating-option input');
    await choices.first().uncheck();
    assert.equal(await choices.first().isChecked(), false);
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('dialog', { name: '转盘选项' }).isVisible(), true);
    await page.getByRole('dialog', { name: '转盘选项' }).getByRole('button', { name: '关闭', exact: true }).click();
    await page.locator('.workspace-toolbar').getByRole('button', { name: '编辑', exact: true }).first().click();
    await page.getByRole('dialog', { name: '编辑转盘' }).waitFor();
    await page.getByLabel('名称', { exact: true }).fill('草稿测试');
    await page.getByRole('dialog', { name: '编辑转盘' }).getByRole('button', { name: '关闭', exact: true }).click();
    assert.equal(await page.locator('.wheel-stage-panel h2').textContent(), '担当大臣');
    await page.getByRole('button', { name: '旋转转盘' }).click();
    await page.waitForTimeout(400);
    assert.equal(await page.getByRole('button', { name: '旋转转盘' }).isDisabled(), false);
    assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('.decision-wheel')).transform !== 'none'), true);
    await page.waitForTimeout(4000);
    assert.notEqual(await page.locator('.desktop-wheel-result strong').textContent(), '???');
    console.log('PASS wheel modal, cancelled draft, disabled choice and spin');

    await page.getByRole('button', { name: '随机数字', exact: true }).click();
    await page.getByLabel('最小值').fill('1');
    await page.getByLabel('最大值').fill('9');
    await page.getByLabel('数量', { exact: true }).fill('9');
    await page.getByRole('button', { name: '生成', exact: true }).click();
    await page.waitForTimeout(500);
    await page.screenshot({ path: path.join(output, 'number-animation.png') });
    assert.equal(await page.getByLabel('最小值').isDisabled(), true);
    await page.waitForTimeout(4000);
    const numbers = await page.evaluate(() => JSON.parse(localStorage.getItem('xiaojd-desktop:v1')).history.find((item) => item.type === 'number').result);
    assert.equal(numbers.length, 9); assert.equal(new Set(numbers).size, 9);
    await page.screenshot({ path: path.join(output, 'number-results.png') });
    await page.getByLabel('最小值').fill('0.5');
    assert.equal(await page.getByRole('button', { name: '生成', exact: true }).isDisabled(), true);
    console.log('PASS number generation, no duplicates, frozen config and invalid input');

    await page.getByRole('button', { name: '抛硬币', exact: true }).first().click();
    await page.locator('.coin-command').click();
    await page.locator('.coin-media video').waitFor();
    await page.waitForFunction(() => document.querySelector('video')?.currentTime > 0.3);
    const video = await page.locator('.coin-media video').evaluate((element) => {
      const canvas = document.createElement('canvas'); canvas.width = 64; canvas.height = 64;
      const ctx = canvas.getContext('2d'); ctx.drawImage(element, 0, 0, 64, 64);
      const pixels = ctx.getImageData(0, 0, 64, 64).data;
      return { width: element.videoWidth, height: element.videoHeight, time: element.currentTime, duration: element.duration, nonwhite: Array.from(pixels).filter((v, i) => i % 4 !== 3 && v < 230).length };
    });
    assert.ok(video.width > 0 && video.nonwhite > 50);
    await page.screenshot({ path: path.join(output, 'coin-animation.png') });
    await page.locator('.coin-command').waitFor({ state: 'visible' });
    await page.waitForFunction(() => !document.querySelector('.coin-command').disabled, { timeout: 15000 });
    assert.match(await page.locator('.coin-result').textContent(), /正面|反面/);
    await page.screenshot({ path: path.join(output, 'coin-result.png') });
    console.log('PASS original coin video frames and result', JSON.stringify(video));

    await page.getByRole('button', { name: '定时转动', exact: true }).click();
    await page.getByRole('button', { name: '添加定时', exact: true }).click();
    const start = new Date(Date.now() + 75000); start.setSeconds(0, 0);
    const end = new Date(start.getTime() + 120000);
    const hhmm = (date) => `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
    await page.getByLabel('开始时间').fill(hhmm(start));
    await page.getByLabel('结束时间').fill(hhmm(end));
    await page.getByLabel('时间间隔（分钟）').fill('1');
    await page.getByRole('button', { name: '保存定时', exact: true }).click();
    await page.locator('.schedule-row').waitFor();
    await page.screenshot({ path: path.join(output, 'schedule-desktop.png') });
    const saved = await page.evaluate(() => window.desktop.getScheduler());
    assert.equal(saved.schedules.length, 1);
    const popupPromise = application.waitForEvent('window', { timeout: 90000 });
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find((window) => !window.webContents.getURL().includes('mode=scheduled')).close());
    assert.equal(await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isVisible()), false);
    console.log('WAIT scheduled background spin at', start.toISOString());
    const popup = await popupPromise;
    await popup.locator('.scheduled-result').waitFor();
    await popup.getByRole('button', { name: '知道了' }).waitFor();
    await popup.waitForFunction(() => !document.querySelector('.scheduled-card .save-button').disabled, { timeout: 15000 });
    await popup.screenshot({ path: path.join(output, 'scheduled-popup.png') });
    const resultState = await popup.evaluate(() => window.desktop.getScheduler());
    assert.equal(resultState.results.length, 1);
    assert.equal(await popup.locator('.scheduled-result').textContent(), resultState.results[0].result);
    await popup.getByRole('button', { name: '知道了' }).click();
    await application.close(); application = undefined;
    application = await launch();
    const restarted = await application.firstWindow();
    await restarted.waitForFunction(() => Boolean(window.desktop));
    const restored = await restarted.evaluate(() => window.desktop.getScheduler());
    assert.equal(restored.schedules.length, 1); assert.equal(restored.results.length, 1);
    assert.equal(restored.results[0].acknowledged, true);
    console.log('PASS background close-to-tray, scheduled popup, persisted result and task');
    await restarted.evaluate(async () => { const state = await window.desktop.getScheduler(); await window.desktop.saveSchedules(state.schedules.map((item) => ({ ...item, enabled: false }))); });
    await restarted.setViewportSize({ width: 390, height: 844 });
    await restarted.screenshot({ path: path.join(output, 'wheel-mobile.png'), fullPage: true });
    assert.equal(await restarted.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.deepEqual(errors, []);
    console.log('PASS layout and no renderer exceptions; evidence:', output);
  } finally {
    if (application) await application.close();
    vite.kill();
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
